### PR TITLE
Update index.yaml after rebuilding it

### PR DESCRIPTION
**Pull request by jonyoder**
Updates index.yaml for `helm.rstudio.com/index.yaml` after rebuilding it.

### CODE REVIEW

**Comment by colearendt** [comment]
Do we have two entries for rstudio-pm-0.2.0-rc03? Any ideas for why that is?

**Comment by jonyoder** [comment]
@colearendt I noticed that and I have no idea why!

**Comment by jonyoder** [comment]
Oh, I'll bet it appended it since the existing `index.yaml` already had it.

**Comment by jonyoder** [comment]
@colearendt The problem was that we were using `https://helm.rstudio.com` as the helm repo when generating the index. This grabbed the existing index.yaml and appended all the rebuilt packages to it. I changed the default to `https://rstudio.com` instead so the index gets rebuilt from nothing. It's annoying since it must be a valid domain but must 404.

**Review by colearendt — APPROVED** [review]
Very strange!! Sounds like chart-releaser has some work to do to make it more idempotent 😬 

In any case, thanks for doing this digging! Now we know a lot more about how chart-releaser works, which is encouraging since we are building on top of it!

**Comment by jonyoder** [comment]
I realized that the digest values are changing, and won't match the SHA256 checksums of the files on Github. I'll work on an alternate approach for the script.

**Comment by colearendt** [comment]
Maybe this is the reason that cr is not idempotent? Maybe its digests are not consistent either? I don’t know enough about how that index.yaml is generated, I don’t think.

**Comment by jonyoder** [comment]
It should be good now!

**Comment by colearendt** [comment]
Well done! LGTM!

**Pull request merged**
