### PR TITLE
update rbac to allow reading of service acccounts

### PR DESCRIPTION
**Pull request by zackverham**
This PR modifies the `rbac` template to allow Launcher to read the available enumeration of service accounts. 
Needed for https://github.com/rstudio/connect/issues/22722 and follow-up service account work.

### CODE REVIEW

**Comment by dbkegley** [comment]
@colearendt Since we need to modify the rstudio-library chart and the launcher-rbac chart version, do we need separate PRs or can we bump the version for both in the same PR?

**Review by AlexMapley — COMMENTED** [review]
I have no problem allowing easier listing of our serviceaccounts, and I can see how this would be helpful reading https://github.com/rstudio/connect/issues/22722.

But yeah building off @dbkegley's [comment](https://github.com/rstudio/helm/pull/329?notification_referrer_id=NT_kwDOARyPq7M1MzE1ODg1ODkxOjE4NjQ5MDAz#issuecomment-1382207243) though, I think we can use https://github.com/rstudio/helm/commit/6a8c4b93ea6684b7f964b37f79e2f6b2d49e7718 as a reference for how we'll want to version these chart updates

**Comment by zackverham** [comment]
ok - I think I have the version bumps as expected now. 

Apologies for needing to give this a few passes, I'm new to Helm!

**Comment by dbkegley** [comment]
I'm not sure we should be updating the workbench version in this PR.

Do we also need news in the `rstudio-pm` and `rstudio-workbench` charts noting the changes to the RBAC rules inherited from the `rstudio-library` chart? This PR will need to merge soon after the next Connect release, sometime next week.

cc @colearendt

**Review by colearendt — APPROVED** [review]
LGTM!

**Comment by zackverham** [comment]
# Testing Notes: 

Running Connect against the non-updated helm charts prints the expected error message

```
time="2023-02-09T13:55:52.123Z" level=info msg="Starting the launcher..."
time="2023-02-09T13:55:52.154Z" level=info msg="2023-02-09T13:55:52.153741Z [rstudio-launcher] INFO Bootstrapping plugin Kubernetes" stream=stderr subprocess=rstudio-launcher
time="2023-02-09T13:55:52.364Z" level=info msg="2023-02-09T13:55:52.363903Z [rstudio-kubernetes-launcher, log-source: Kubernetes] INFO Permission to list nodes denied by the Kubernetes API server. This is fine in most cases, but IP addresses for jobs with a NodePort will reflect only the cluster's own IP range -- which may not be visible to an external service. Consider adding a nodes' ClusterRole for the ServiceAccount if network connectivity from outside the cluster is an issue." stream=stderr subprocess=rstudio-launcher
time="2023-02-09T13:55:52.384Z" level=info msg="2023-02-09T13:55:52.383925Z [rstudio-kubernetes-launcher, log-source: Kubernetes] INFO Permission to list Service Accounts denied by the Kubernetes API server. Jobs can still specify a Service Account by name, but the list of available Service Accounts will not be exposed to clients.Consider updating the Kubernetes Role for Launcher's own Service Account to make these accessible." stream=stderr subprocess=rstudio-launcher
```

Running Connect against the updated rbac definition removes the permission log / warning:

```
time="2023-02-09T13:58:03.076Z" level=info msg="Starting the launcher..."
time="2023-02-09T13:58:03.081Z" level=info msg="2023-02-09T13:58:03.081681Z [rstudio-launcher] INFO Bootstrapping plugin Kubernetes" stream=stderr subprocess=rstudio-launcher
time="2023-02-09T13:58:03.254Z" level=info msg="2023-02-09T13:58:03.254436Z [rstudio-kubernetes-launcher, log-source: Kubernetes] INFO Permission to list nodes denied by the Kubernetes API server. This is fine in most cases, but IP addresses for jobs with a NodePort will reflect only the cluster's own IP range -- which may not be visible to an external service. Consider adding a nodes' ClusterRole for the ServiceAccount if network connectivity from outside the cluster is an issue." stream=stderr subprocess=rstudio-launcher
time="2023-02-09T13:58:03.274Z" level=info msg="2023-02-09T13:58:03.274010Z [rstudio-kubernetes-launcher, log-source: Kubernetes] INFO Pruning 0 jobs" stream=stderr subprocess=rstudio-launcher
time="2023-02-09T13:58:03.276Z" level=info msg="2023-02-09T13:58:03.276060Z [rstudio-launcher] INFO Initializing SslAsyncServer [address: 0.0.0.0, port: 5559]" stream=stderr subprocess=rstudio-launcher
time="2023-02-09T13:58:03.277Z" level=info msg="2023-02-09T13:58:03.277566Z [rstudio-launcher] INFO Running server" stream=stderr subprocess=rstudio-launcher

```

**Review by dbkegley — APPROVED** [review]

**Pull request merged**
