### PR TITLE
add pip.conf mount to /etc/pip.conf

### LINKED ISSUE #405: Workbench pip.conf configuration should automatically create a volume mount in the session pod
Currently, there isn't a canonical way for customers to define a pip.conf in our Workbench chart, such that it will be correctly picked up by pip in our session images. We should automate this process for customers, since many, if not the majority, will want to configure a configure pip.conf to define their internal pypi repos. This could be done under the `session.pip.conf` configuration and then we create a volumeMount to mount this file directly over /etc/pip.conf.

### PR DESCRIPTION
**Pull request by colearendt**
close #405 

Although we still need to think about Connect configuration for sessions too 🤷

### CODE REVIEW

**Review by samcofer — APPROVED** [review]
Looks good to me!

**Comment by samcofer** [comment]
Just did some additional testing here and I'm not seeing the volume mount in the pod for /etc/pip.conf. It's working in workbench, but not in the session pod.

**Comment by samcofer** [comment]
Mistake on my part, missed enabling templating. Looks good and working as intended!

**Comment by SamEdwardes** [comment]
Hey team - apologies I do not have time to review this before my time off!

**Pull request merged**
