### PR TITLE
Service account labels

### LINKED ISSUE #391: add ability to modify labels in rbac.serviceAccount
Currently helm value `rbac.serviceAccount` supports the following format: `{"annotations":{},"create":true,"name":""}`.
Could we get this to accept `labels` as well?

Setting up Azure Workload Identity needs this
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID}
  labels:
    azure.workload.identity/use: "true"
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: ${SERVICE_ACCOUNT_NAMESPACE}
```

### PR DESCRIPTION
**Pull request by samssann**
Fixes #391 

Allows one to assign labels in service accounts in rstudio-workbench and rstudio-connect charts.

### CODE REVIEW

**Comment by samssann** [comment]
@colearendt what steps are required to move forward with this?

**Comment by samssann** [comment]
@atheriel ?

**Comment by atheriel** [comment]
Content and approach looks fine to me, but I'll defer to Cole on fixing CI.

**Comment by colearendt** [comment]
This looks great! Thanks so much for the submission! Hoping to get to this sometime this week as I keep catching up from vacation 😄

**Review by colearendt — APPROVED** [review]
LGTM! I just added a handful of boilerplate:
- add default values and some comments
- trace version changes through the stack
- update docs so that they match CI

**Pull request merged**
