### PR TITLE
Fix posit-chronicle to function with default values

### PR DESCRIPTION
**Pull request by jforest**
Initial error with the empty values file is: `Error: failed to create metrics service: no storers found for v1/metrics`

Setting `LocalStorage.Enabled` to `true` fixes the empty values file problem

I also added a few more CODEOWNERS.  I made some guesses on who makes sense for which based on who has made commits to those charts, and those who I am fairly sure are involved. 

So, sorry @matt-urbina @markrtucker  @AshleyHenry15 @GCRev and @zachhannum if you are not the proper people.  If you could give me some better names I will be happy to update the lists

### CODE REVIEW

**Comment by edavidaja** [comment]
I'm not particularly involved in any chart maintenance; I set up the [documentation site](https://docs.posit.co/helm).

**Comment by jforest** [comment]
> I'm not particularly involved in any chart maintenance; I set up the [documentation site](https://docs.posit.co/helm).

Removed!

**Comment by edavidaja** [comment]
I believe Ashley's involvement was also primarily docs-related.

**Review by GCRev — APPROVED** [review]
LGTM

**Comment by jforest** [comment]
At https://github.com/rstudio/helm/tree/main/charts/posit-chronicle#storage-configuration we say the default is local storage, so this is changing the code to match the documentation

image

**Review by t-margheim — APPROVED** [review]
LGTM!

**Review by matt-urbina — APPROVED** [review]
Looks good!

**Pull request merged**
