### PR TITLE
Bump Workbench version to 2024.09.0

### PR DESCRIPTION
**Pull request by zachhannum**

### CODE REVIEW

**Review by GCRev — APPROVED** [review]
I don't see anything wrong here. Hopefully those image tags exist already.

**Comment by zachhannum** [comment]
@GCRev They don't yet, so this PR shouldn't be merged until they do. Pending the merge of rstudio/rstudio-docker-products#845

**Comment by GCRev** [comment]
I feel like we've been on 2024.09 for long-enough now that we should have docker builds of it, but maybe I'm thinking about the preview tags here: https://hub.docker.com/r/rstudio/r-session-complete-preview/tags

**Comment by bschwedler** [comment]
The `2024.09.0` images have now been built from `main` on rstudio/rstudio-docker-products

**Review by bschwedler — APPROVED** [review]

**Pull request merged**
