### PR TITLE
Cluster role create

### PR DESCRIPTION
**Pull request by kfeinauer**
Make `ClusterRole` creation optional, false by default. This goes along with https://github.com/rstudio/launcher/pull/210

### CODE REVIEW

**Review by jonyoder — APPROVED** [review]

**Review by colearendt — CHANGES_REQUESTED** [review]
This looks awesome!

Just need to update the `rstudio-library` chart version in `Chart.yaml` under dependencies for `rstudio-connect`, rstudio-workbench`, and `rstudio-launcher-rbac` 😄

**Comment by colearendt** [comment]
A few more nits - it looks like linting is failing on empty lines and extra whitespace in `Chart.yaml` 🙈 

Also, probably worth adding some NEWS.md entries because people will see their cluster roles disappearing on upgrade. That way they can anticipate it, and know what value reverts if they care to keep the cluster role around.

**Comment by kfeinauer** [comment]
Okay @colearendt this should be good to go now. Linting/installing is working properly now.

**Review by colearendt — APPROVED** [review]
Woohoo!! Looks awesome!! Thanks for handling this!

**Pull request merged**
